### ISSUE TITLE
[Template Request] Graduation Thesis Template

### ISSUE THREAD

**Issue by PumpkinCheshire** [bimalka98/LaTeX-Templates#3]
It would be great if there is a complete graduation thesis template, or a research thesis template.

**Comment by bimalka98** [comment]
I'm afraid @PumpkinCheshire  I don't have any graduation thesis template or a research thesis template to be uploaded at the moment.  But I could find one which belongs to one of the graduate students of my university.  Here is the link. https://github.com/kahnchana/fyp_report  It's readme contains all info necessary to generate/edit the final document.
